### PR TITLE
remove floaty particles overlay

### PR DESCRIPTION
**Pull request by jrochkind**
The "floaty particles" overlay actually makes pages hard to read, as the floaty particles go over text. It also, in the opinions of some audience, just kind of looks messy. It is of unclear purpose. 

In an email @adarsh wrote to me that rubycentral lacked resources for website design adjustment, but invited a PR. 

**Warning**: I haven't actually run/tested this code, this PR was done blind only based on code/history read. I am not familiar with `ghost`, and found the install/test instructions in the README somewhat overwhelming and outside of my current available time. So this should probably be tested by someone, and/or deployed carefully with option for immediate rollback? 

Or if there's CI, that's at least something! 

This is a partial revert of @indirect's 106afb32b, so perhaps @indirect would have some feedback about the original intention of the "floaty particles" overlay and if it is objectionable to remove (or there is some other way to improve it); or about the technical details of the revert, if anything was missed.

### CODE REVIEW

**Comment by indirect** [comment]
I sadly do not have any insight into the particles--I was simply porting them forward from the existing design while setting up Ghost. If the powers that be are happy to remove them, it sounds fine to me.

**Comment by jrochkind** [comment]
Hi, if the blocker is that I haven't figured out how to test the theme locally myself, I can try to find time to do that. But I'd rather not find the time to do that if the end result will be no different, and the team is actually just interested and/or not capable of merging this. @adarsh ?

**Comment by indirect** [comment]
I merged the other PR that removes the particles entirely for users who have requested less motion from their UI. Does that work for you?

**Comment by jrochkind** [comment]
Oh, I see. 

Not really for me, no. I don't know how to, and have no desire to, set a preference to "reduce motion" in my entire UI or browser. 

Here is what I originally contact@rubycentral.org:

> I really like Ruby Central as an organization. I am glad you exist. I try to pay attention to you and promote you. 

> The animated background on your website is... really distracting, and unprofessional looking, and literally makes it hard to read your webpages, as well as making people wonder if something is wrong with their screen or browser until they figure out it's your website. 

> I sometimes post links from your site to reddit, eg https://rubycentral.org/news/jointheboard/

> When I do, usually someone comments about how terrible and distracting the animated "moving particles" background is. 

> I don't really understand what you're trying to do with it, but I think you might want to reconsider!

@adarsh responded saying there were no resources for ruby central web design, but saying "feel free to open a PR". 

So i did, spent some time investigating, put together the PR. 

Here are a couple more examples of upvoted comments on reddit, from different people, saying what's up with that weird floaty background, with replies agreeing. 

* https://www.reddit.com/r/ruby/comments/12elplj/what_we_do_at_ruby_central/jfbn24j/
* https://www.reddit.com/r/ruby/comments/10szvoh/ruby_shield_update_a_ruby_security_partnership/j75pv0b/

I think the floaties make rubycentral look unprofessional. 

That's all I got. The decision of course is not mine, it's whatever the relevant rubycentral decision-making process is.  If you are not interested in this PR, feel free to close it?

**Comment by bigtiger** [comment]
@jrochkind Thank you for this PR. I do feel like it's worth addressing the accessibility of the RubyCentral site. @codyjamesbrooks proposed and @indirect merged #16 to respect the `[prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion)` setting of your operating system. There are details in the **[User Preferences](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#user_preferences)** section of the link above.

I don't have the ability to close this PR but, I'll make sure that happens.

**Comment by indirect** [comment]
Done in #17.

**Pull request closed without merging**
